[project]
name = "my-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "joaquinVazquez", email = "joaquin.vazquez@unisa.edu.mx" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.1",
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
]


[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "langgraph-cli[inmem]>=0.4.31",
]

[tool.uv.build-backend]
module-name = ["agents", "api"]
